# tasks for Debian Familly
---

- name: Download Percona package
  get_url: 
    url="https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
    dest="/percona-release_latest.generic_all.deb"
  register: percona_package_check_deb
  
- name: Install Percona package
  apt: deb="/percona-release_latest.generic_all.deb"
  when: percona_package_check_deb.changed == 1  
  
- name: update cache
  apt:
    update_cache: yes
  changed_when: false
...
